<?php
namespace AutoDealership\Admin;

use AutoDealership\Branches\BranchService;
use AutoDealership\Reference\ReferenceService;

defined( 'ABSPATH' ) || exit;

final class ReferencePage {
	public static function boot(): void {
		add_action( 'admin_menu', array( self::class, 'menu' ) );
		foreach ( array( 'adc_create_brand','adc_create_location','adc_toggle_reference' ) as $action ) { add_action( 'admin_post_' . $action, array( self::class, $action ) ); }
	}
	public static function menu(): void { add_submenu_page( 'adc-settings', __( 'Brands and locations', 'auto-dealership-core' ), __( 'Brands and locations', 'auto-dealership-core' ), 'manage_options', 'adc-reference', array( self::class, 'render' ) ); }
	public static function render(): void {
		if ( ! current_user_can( 'manage_options' ) ) { wp_die( esc_html__( 'Administrator access is required.', 'auto-dealership-core' ), '', array( 'response' => 403 ) ); }
		$brands = ReferenceService::brands(); $locations = ReferenceService::locations(); $branches = BranchService::public_list(); ?>
		<div class="wrap" dir="<?php echo 'en' === \AutoDealership\Core\Localization::language() ? 'ltr' : 'rtl'; ?>"><h1><?php esc_html_e( 'العلامات التجارية والمواقع', 'auto-dealership-core' ); ?></h1><?php if ( isset( $_GET['saved'] ) ) : ?><div class="notice notice-success"><p><?php esc_html_e( 'تم حفظ البيانات المرجعية.', 'auto-dealership-core' ); ?></p></div><?php endif; ?><?php if ( isset( $_GET['error'] ) ) : ?><div class="notice notice-error"><p><?php esc_html_e( 'تعذر تنفيذ العملية. تحقق من القيم ومن عدم ارتباط المرجع بمركبة نشطة.', 'auto-dealership-core' ); ?></p></div><?php endif; ?>
		<h2><?php esc_html_e( 'إضافة علامة', 'auto-dealership-core' ); ?></h2><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><input type="hidden" name="action" value="adc_create_brand"><?php wp_nonce_field( 'adc_create_brand' ); ?><input name="key" placeholder="<?php echo esc_attr__( 'brand-key', 'auto-dealership-core' ); ?>" required> <input name="name_ar" placeholder="<?php echo esc_attr__( 'الاسم العربي', 'auto-dealership-core' ); ?>" required> <input name="name_en" placeholder="<?php echo esc_attr__( 'English name', 'auto-dealership-core' ); ?>"> <?php submit_button( __( 'إضافة', 'auto-dealership-core' ), 'secondary', 'submit', false ); ?></form>
		<table class="widefat striped"><thead><tr><th><?php esc_html_e( 'المفتاح', 'auto-dealership-core' ); ?></th><th><?php esc_html_e( 'الاسم', 'auto-dealership-core' ); ?></th><th><?php esc_html_e( 'الحالة', 'auto-dealership-core' ); ?></th></tr></thead><tbody><?php foreach ( $brands as $row ) : ?><?php self::row( 'brand', $row, $row['brand_key'], ( 'en' === \AutoDealership\Core\Localization::language() && $row['name_en'] ? $row['name_en'] : $row['name_ar'] ) ); ?><?php endforeach; ?></tbody></table>
		<h2><?php esc_html_e( 'إضافة موقع', 'auto-dealership-core' ); ?></h2><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><input type="hidden" name="action" value="adc_create_location"><?php wp_nonce_field( 'adc_create_location' ); ?><select name="branch_id" required><?php foreach ( $branches as $branch ) : ?><option value="<?php echo absint( $branch['id'] ); ?>"><?php echo esc_html( \AutoDealership\Content\StoredTranslations::text( 'branches', (int) $branch['id'], 'name', (string) $branch['name'] ) ); ?></option><?php endforeach; ?></select> <input name="code" placeholder="<?php echo esc_attr__( 'LOCATION-CODE', 'auto-dealership-core' ); ?>" required> <input name="name" placeholder="<?php echo esc_attr__( 'اسم الموقع', 'auto-dealership-core' ); ?>" required> <select name="type"><option value="showroom"><?php echo esc_html__( 'showroom', 'auto-dealership-core' ); ?></option><option value="warehouse"><?php echo esc_html__( 'warehouse', 'auto-dealership-core' ); ?></option><option value="yard"><?php echo esc_html__( 'yard', 'auto-dealership-core' ); ?></option><option value="service"><?php echo esc_html__( 'service', 'auto-dealership-core' ); ?></option></select> <?php submit_button( __( 'إضافة', 'auto-dealership-core' ), 'secondary', 'submit', false ); ?></form>
		<table class="widefat striped"><thead><tr><th><?php esc_html_e( 'الرمز', 'auto-dealership-core' ); ?></th><th><?php esc_html_e( 'الموقع والفرع', 'auto-dealership-core' ); ?></th><th><?php esc_html_e( 'الحالة', 'auto-dealership-core' ); ?></th></tr></thead><tbody><?php foreach ( $locations as $row ) : ?><?php self::row( 'location', $row, $row['code'], \AutoDealership\Content\StoredTranslations::text( 'locations', (int) $row['id'], 'name', (string) $row['name'] ) . ' — ' . \AutoDealership\Content\StoredTranslations::text( 'branches', (int) $row['branch_id'], 'name', (string) $row['branch_name'] ) . ' (' . \AutoDealership\Core\Localization::label( (string) $row['location_type'] ) . ')' ); ?><?php endforeach; ?></tbody></table></div><?php
	}
	private static function row( string $kind, array $row, string $code, string $name ): void { ?><tr><td><code><?php echo esc_html( $code ); ?></code></td><td><?php echo esc_html( $name ); ?></td><td><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><input type="hidden" name="action" value="adc_toggle_reference"><input type="hidden" name="kind" value="<?php echo esc_attr( $kind ); ?>"><input type="hidden" name="id" value="<?php echo absint( $row['id'] ); ?>"><input type="hidden" name="active" value="<?php echo empty( $row['active'] ) ? '1' : '0'; ?>"><?php wp_nonce_field( 'adc_toggle_reference_' . $kind . '_' . (int) $row['id'] ); ?><button class="button"><?php echo empty( $row['active'] ) ? esc_html__( 'تفعيل', 'auto-dealership-core' ) : esc_html__( 'تعطيل', 'auto-dealership-core' ); ?></button></form></td></tr><?php }
	/**
	 * @param mixed $result
	 */
	private static function redirect( $result ): void { wp_safe_redirect( add_query_arg( is_wp_error( $result ) ? 'error' : 'saved', '1', admin_url( 'admin.php?page=adc-reference' ) ) ); exit; }
	public static function adc_create_brand(): void { check_admin_referer( 'adc_create_brand' ); self::redirect( ReferenceService::create_brand( array( 'key' => wp_unslash( $_POST['key'] ?? '' ), 'name_ar' => wp_unslash( $_POST['name_ar'] ?? '' ), 'name_en' => wp_unslash( $_POST['name_en'] ?? '' ) ) ) ); }
	public static function adc_create_location(): void { check_admin_referer( 'adc_create_location' ); self::redirect( ReferenceService::create_location( array( 'branch_id' => wp_unslash( $_POST['branch_id'] ?? '' ), 'code' => wp_unslash( $_POST['code'] ?? '' ), 'name' => wp_unslash( $_POST['name'] ?? '' ), 'type' => wp_unslash( $_POST['type'] ?? '' ) ) ) ); }
	public static function adc_toggle_reference(): void { $kind = sanitize_key( wp_unslash( $_POST['kind'] ?? '' ) ); $id = absint( $_POST['id'] ?? 0 ); check_admin_referer( 'adc_toggle_reference_' . $kind . '_' . $id ); self::redirect( ReferenceService::set_active( $kind, $id, ! empty( $_POST['active'] ) ) ); }
}
