<?php
namespace AutoDealership\Admin;

use AutoDealership\Payments\RefundService;

defined( 'ABSPATH' ) || exit;

final class RefundPage {
	public static function boot(): void {
		add_action( 'admin_menu', array( self::class, 'menu' ) );
		add_action( 'admin_post_adc_request_refund', array( self::class, 'request' ) );
		add_action( 'admin_post_adc_decide_refund', array( self::class, 'decide' ) );
	}
	public static function menu(): void { add_submenu_page( 'adc-finance', __( 'Refunds', 'auto-dealership-core' ), __( 'Refunds', 'auto-dealership-core' ), 'adc_view_finance', 'adc-refunds', array( self::class, 'render' ) ); }
	public static function render(): void {
		if(!current_user_can('adc_view_finance')){wp_die('', '',array('response'=>403));}
		$returns=RefundService::refundable_returns();$cancellations=RefundService::refundable_cancellations();$reservations=RefundService::refundable_reservations();$refunds=RefundService::list_for_current_user(); ?>
		<div class="wrap" dir="<?php echo 'en' === \AutoDealership\Core\Localization::language() ? 'ltr' : 'rtl'; ?>"><h1><?php echo esc_html__( 'الاستردادات المالية', 'auto-dealership-core' ); ?></h1><p><?php echo esc_html__( 'توثق هذه الشاشة استردادًا منفذًا خارج النظام، ولا تنقل أموالًا.', 'auto-dealership-core' ); ?></p>
		<?php if(current_user_can('adc_record_refunds')):?><form class="card" method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="adc_request_refund"><?php wp_nonce_field('adc_request_refund');?><select name="return_id" required><option value=""><?php echo esc_html__( 'الإرجاع', 'auto-dealership-core' ); ?></option><?php foreach($returns as $row):?><option value="<?php echo absint($row['id']);?>"><?php echo esc_html($row['stock_number'].' — #'.$row['sale_id']);?></option><?php endforeach;?></select><input type="number" min="1" step="1" name="amount" required placeholder="<?php echo esc_attr__( 'المبلغ بالهللات', 'auto-dealership-core' ); ?>"><select name="method"><option value="cash_refund"><?php echo esc_html__( 'نقدي', 'auto-dealership-core' ); ?></option><option value="bank_transfer"><?php echo esc_html__( 'تحويل بنكي', 'auto-dealership-core' ); ?></option><option value="finance_reversal"><?php echo esc_html__( 'عكس تمويل', 'auto-dealership-core' ); ?></option></select><input name="reference" maxlength="100" required placeholder="<?php echo esc_attr__( 'مرجع الاسترداد', 'auto-dealership-core' ); ?>"><button class="button button-primary"><?php echo esc_html__( 'إرسال للمراجعة', 'auto-dealership-core' ); ?></button></form><?php endif;?>
		<?php if(current_user_can('adc_record_refunds')&&$cancellations):?><form class="card" method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="adc_request_refund"><?php wp_nonce_field('adc_request_refund');?><select name="cancellation_id" required><option value=""><?php echo esc_html__( 'إلغاء البيع', 'auto-dealership-core' ); ?></option><?php foreach($cancellations as $row):?><option value="<?php echo absint($row['id']);?>"><?php echo esc_html($row['stock_number'].' — #'.$row['sale_id']);?></option><?php endforeach;?></select><input type="number" min="1" step="1" name="amount" required placeholder="<?php echo esc_attr__( 'المبلغ بالهللات', 'auto-dealership-core' ); ?>"><select name="method"><option value="cash_refund"><?php echo esc_html__( 'نقدي', 'auto-dealership-core' ); ?></option><option value="bank_transfer"><?php echo esc_html__( 'تحويل بنكي', 'auto-dealership-core' ); ?></option><option value="finance_reversal"><?php echo esc_html__( 'عكس تمويل', 'auto-dealership-core' ); ?></option></select><input name="reference" maxlength="100" required placeholder="<?php echo esc_attr__( 'مرجع الاسترداد', 'auto-dealership-core' ); ?>"><button class="button button-primary"><?php echo esc_html__( 'استرداد إلغاء البيع', 'auto-dealership-core' ); ?></button></form><?php endif;?>
		<?php if(current_user_can('adc_record_refunds')&&$reservations):?><form class="card" method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="adc_request_refund"><?php wp_nonce_field('adc_request_refund');?><select name="reservation_id" required><option value=""><?php esc_html_e('Cancelled reservation deposit','auto-dealership-core');?></option><?php foreach($reservations as $row):?><option value="<?php echo absint($row['id']);?>"><?php echo esc_html($row['stock_number'].' — #'.$row['id'].' / '.$row['deposit_amount']);?></option><?php endforeach;?></select><input type="number" min="1" step="1" name="amount" required placeholder="<?php echo esc_attr__( 'Amount in halalas', 'auto-dealership-core' ); ?>"><select name="method"><option value="cash_refund"><?php echo esc_html__( 'cash', 'auto-dealership-core' ); ?></option><option value="bank_transfer"><?php echo esc_html__( 'bank transfer', 'auto-dealership-core' ); ?></option><option value="finance_reversal"><?php echo esc_html__( 'finance reversal', 'auto-dealership-core' ); ?></option></select><input name="reference" maxlength="100" required placeholder="<?php echo esc_attr__( 'Refund reference', 'auto-dealership-core' ); ?>"><button class="button button-primary"><?php esc_html_e('Record reservation deposit refund','auto-dealership-core');?></button></form><?php endif;?>
		<table class="widefat striped"><thead><tr><th><?php echo esc_html__( 'المركبة', 'auto-dealership-core' ); ?></th><th><?php echo esc_html__( 'المبلغ', 'auto-dealership-core' ); ?></th><th><?php echo esc_html__( 'المرجع', 'auto-dealership-core' ); ?></th><th><?php echo esc_html__( 'الحالة', 'auto-dealership-core' ); ?></th><th><?php echo esc_html__( 'القرار', 'auto-dealership-core' ); ?></th></tr></thead><tbody><?php foreach($refunds as $row):?><tr><td><?php echo esc_html($row['stock_number']);?></td><td><?php echo esc_html(number_format_i18n((int)$row['amount']));?></td><td><?php echo esc_html($row['reference']);?></td><td><?php echo esc_html( \AutoDealership\Core\Localization::label( (string) $row['status'] ) );?></td><td><?php if(current_user_can('adc_verify_refunds')&&'pending'===$row['status']&&(int)$row['requested_by']!==get_current_user_id()):?><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="adc_decide_refund"><input type="hidden" name="id" value="<?php echo absint($row['id']);?>"><?php wp_nonce_field('adc_decide_refund_'.(int)$row['id']);?><select name="decision"><option value="approve"><?php echo esc_html__( 'اعتماد', 'auto-dealership-core' ); ?></option><option value="reject"><?php echo esc_html__( 'رفض', 'auto-dealership-core' ); ?></option></select><input name="reason" required placeholder="<?php echo esc_attr__( 'سبب القرار', 'auto-dealership-core' ); ?>"><button class="button"><?php echo esc_html__( 'حفظ', 'auto-dealership-core' ); ?></button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></div><?php
	}
	private static function input(string $key):string{return isset($_POST[$key])&&is_string($_POST[$key])?wp_unslash($_POST[$key]):'';}
	private static function redirect($result):void{wp_safe_redirect(add_query_arg(is_wp_error($result)?'error':'saved','1',admin_url('admin.php?page=adc-refunds')));exit;}
	public static function request():void{check_admin_referer('adc_request_refund');$reservation=absint(self::input('reservation_id'));$cancellation=absint(self::input('cancellation_id'));$result=$reservation?RefundService::request_reservation($reservation,absint(self::input('amount')),self::input('method'),self::input('reference')):($cancellation?RefundService::request_cancellation($cancellation,absint(self::input('amount')),self::input('method'),self::input('reference')):RefundService::request(absint(self::input('return_id')),absint(self::input('amount')),self::input('method'),self::input('reference')));self::redirect($result);}
	public static function decide():void{$id=absint(self::input('id'));check_admin_referer('adc_decide_refund_'.$id);$decision=self::input('decision');self::redirect(in_array($decision,array('approve','reject'),true)?RefundService::decide($id,'approve'===$decision,self::input('reason')):new \WP_Error('adc_invalid_refund_decision'));}
}
