<?php
namespace AutoDealership\Admin;
use AutoDealership\Sales\SaleCancellationService;
defined('ABSPATH')||exit;
final class SaleCancellationPage{
	public static function boot():void{add_action('admin_menu',array(self::class,'menu'));add_action('admin_post_adc_cancel_sale',array(self::class,'cancel'));}
	public static function menu():void{add_submenu_page('adc-approvals',__('Sale cancellations','auto-dealership-core'),__('Sale cancellations','auto-dealership-core'),'adc_cancel_sales','adc-sale-cancellations',array(self::class,'render'));}
	public static function render():void{if(!current_user_can('adc_cancel_sales')){wp_die('','',array('response'=>403));}$sales=SaleCancellationService::cancellable_sales();$rows=SaleCancellationService::list_for_current_user();?><div class="wrap" dir="<?php echo 'en' === \AutoDealership\Core\Localization::language() ? 'ltr' : 'rtl'; ?>"><h1><?php echo esc_html__( 'إلغاء المبيعات', 'auto-dealership-core' ); ?></h1><form class="card" method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="adc_cancel_sale"><?php wp_nonce_field('adc_cancel_sale');?><select name="sale_id" required><option value=""><?php echo esc_html__( 'البيع', 'auto-dealership-core' ); ?></option><?php foreach($sales as $row):?><option value="<?php echo absint($row['id']);?>"><?php echo esc_html( '#'.$row['id'].' — '.$row['stock_number'].' — '.\AutoDealership\Core\Localization::label( (string) $row['status'] ) );?></option><?php endforeach;?></select><textarea name="reason" required maxlength="2000" placeholder="<?php echo esc_attr__( 'سبب الإلغاء', 'auto-dealership-core' ); ?>"></textarea><button class="button button-primary"><?php echo esc_html__( 'إلغاء البيع', 'auto-dealership-core' ); ?></button></form><table class="widefat striped"><thead><tr><th><?php echo esc_html__( 'البيع', 'auto-dealership-core' ); ?></th><th><?php echo esc_html__( 'المركبة', 'auto-dealership-core' ); ?></th><th><?php echo esc_html__( 'الحالة السابقة', 'auto-dealership-core' ); ?></th><th><?php echo esc_html__( 'الحالة المالية', 'auto-dealership-core' ); ?></th><th><?php echo esc_html__( 'السبب', 'auto-dealership-core' ); ?></th></tr></thead><tbody><?php foreach($rows as $row):?><tr><td><?php echo absint($row['sale_id']);?></td><td><?php echo esc_html($row['stock_number']);?></td><td><?php echo esc_html( \AutoDealership\Core\Localization::label( (string) $row['previous_sale_status'] ) );?></td><td><?php echo esc_html( \AutoDealership\Core\Localization::label( (string) $row['financial_status'] ) );?></td><td><?php echo esc_html($row['reason']);?></td></tr><?php endforeach;?></tbody></table></div><?php }
	public static function cancel():void{check_admin_referer('adc_cancel_sale');$result=SaleCancellationService::cancel(absint($_POST['sale_id']??0),sanitize_textarea_field(wp_unslash($_POST['reason']??'')));wp_safe_redirect(add_query_arg(is_wp_error($result)?'error':'saved','1',admin_url('admin.php?page=adc-sale-cancellations')));exit;}
}
