<?php
namespace AutoDealership\Admin;
use AutoDealership\Sales\SaleCancellationService;
defined('ABSPATH')||exit;
final class SaleCancellationPage{
	public static function boot():void{add_action('admin_menu',array(self::class,'menu'));add_action('admin_post_adc_cancel_sale',array(self::class,'cancel'));}
	public static function menu():void{add_submenu_page('adc-approvals',__('Sale cancellations','auto-dealership-core'),__('Sale cancellations','auto-dealership-core'),'adc_cancel_sales','adc-sale-cancellations',array(self::class,'render'));}
	public static function render():void{if(!current_user_can('adc_cancel_sales')){wp_die('','',array('response'=>403));}$sales=SaleCancellationService::cancellable_sales();$rows=SaleCancellationService::list_for_current_user();?><div class="wrap" dir="rtl"><h1>إلغاء المبيعات</h1><form class="card" method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="adc_cancel_sale"><?php wp_nonce_field('adc_cancel_sale');?><select name="sale_id" required><option value="">البيع</option><?php foreach($sales as $row):?><option value="<?php echo absint($row['id']);?>"><?php echo esc_html('#'.$row['id'].' — '.$row['stock_number'].' — '.$row['status']);?></option><?php endforeach;?></select><textarea name="reason" required maxlength="2000" placeholder="سبب الإلغاء"></textarea><button class="button button-primary">إلغاء البيع</button></form><table class="widefat striped"><thead><tr><th>البيع</th><th>المركبة</th><th>الحالة السابقة</th><th>الحالة المالية</th><th>السبب</th></tr></thead><tbody><?php foreach($rows as $row):?><tr><td><?php echo absint($row['sale_id']);?></td><td><?php echo esc_html($row['stock_number']);?></td><td><?php echo esc_html($row['previous_sale_status']);?></td><td><?php echo esc_html($row['financial_status']);?></td><td><?php echo esc_html($row['reason']);?></td></tr><?php endforeach;?></tbody></table></div><?php }
	public static function cancel():void{check_admin_referer('adc_cancel_sale');$result=SaleCancellationService::cancel(absint($_POST['sale_id']??0),sanitize_textarea_field(wp_unslash($_POST['reason']??'')));wp_safe_redirect(add_query_arg(is_wp_error($result)?'error':'saved','1',admin_url('admin.php?page=adc-sale-cancellations')));exit;}
}
