<?php
namespace AutoDealership\Admin;

use AutoDealership\Inventory\VehicleIssueService;
use AutoDealership\Inventory\VehicleService;

defined('ABSPATH')||exit;

final class VehicleIssuePage {
	public static function boot():void{add_action('admin_menu',array(self::class,'menu'));add_action('admin_post_adc_open_vehicle_issue',array(self::class,'open'));add_action('admin_post_adc_resolve_vehicle_issue',array(self::class,'resolve'));}
	public static function menu():void{add_submenu_page('adc-workspace',__('Holds and maintenance','auto-dealership-core'),__('Holds and maintenance','auto-dealership-core'),'adc_manage_inventory','adc-vehicle-issues',array(self::class,'render'));}
	public static function render():void{if(!current_user_can('adc_manage_inventory')){wp_die('', '',array('response'=>403));}$section = 'maintenance' === ( $_GET['section'] ?? '' ) ? 'maintenance' : 'hold'; $page = max(1,absint($_GET['paged']??1)); $vehicles=VehicleService::list_for_current_user($page);$issue_page=VehicleIssueService::open_page($section,max(1,absint($_GET['queue_page']??1)),QueueTable::search());$issues=$issue_page['rows'];?>
	<div class="wrap" dir="<?php echo 'en' === \AutoDealership\Core\Localization::language() ? 'ltr' : 'rtl'; ?>"><h1><?php echo esc_html__( 'الاحتجاز والصيانة', 'auto-dealership-core' ); ?></h1><?php Navigation::tabs('adc-vehicle-issues',array('hold'=>'الاحتجاز','maintenance'=>'الصيانة'),$section);  QueueTable::controls('adc-vehicle-issues',$section); ?><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="adc_open_vehicle_issue"><?php wp_nonce_field('adc_open_vehicle_issue');?><select name="vehicle_id"><?php foreach($vehicles as $v):?><option value="<?php echo absint($v['id']);?>"><?php echo esc_html( $v['stock_number'].' — '.\AutoDealership\Core\Localization::label( (string ) $v['status'] ) );?></option><?php endforeach;?></select><input type="hidden" name="type" value="<?php echo esc_attr($section); ?>"><input name="reason" required maxlength="1000" placeholder="<?php echo esc_attr__( 'السبب', 'auto-dealership-core' ); ?>"><input type="date" name="review_at"><button class="button button-primary"><?php echo esc_html__( 'فتح الحالة', 'auto-dealership-core' ); ?></button></form><h2><?php echo esc_html__( 'الحالات المفتوحة', 'auto-dealership-core' ); ?></h2><?php foreach($issues as $issue):?><form class="card" method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="adc_resolve_vehicle_issue"><input type="hidden" name="section" value="<?php echo esc_attr($section); ?>"><input type="hidden" name="id" value="<?php echo absint($issue['id']);?>"><?php wp_nonce_field('adc_resolve_vehicle_issue_'.(int)$issue['id']);?><strong><?php echo esc_html( $issue['stock_number'].' — '.\AutoDealership\Core\Localization::label( (string ) $issue['issue_type'] ) );?></strong><p><?php echo esc_html( \AutoDealership\Content\StoredTranslations::text( 'vehicle_issues', (int) $issue['id'], 'reason', (string) $issue['reason'] ) );?></p><input name="resolution" required maxlength="2000" placeholder="<?php echo esc_attr__( 'الإجراء المنفذ والنتيجة', 'auto-dealership-core' ); ?>"><button class="button"><?php echo esc_html__( 'إغلاق وإعادة للفحص', 'auto-dealership-core' ); ?></button></form><?php endforeach; if(!$issues){echo '<p>'.esc_html__('لا توجد حالات مفتوحة.','auto-dealership-core').'</p>';} QueueTable::footer($issue_page,'adc-vehicle-issues',$section); Navigation::pagination('adc-vehicle-issues',$section,$page,count($vehicles)); ?></div><?php }
	/**
	 * @param mixed $result
	 */
	private static function redirect($result):void{wp_safe_redirect(add_query_arg(is_wp_error($result)?'error':'saved','1',add_query_arg('section','maintenance'===($_POST['section']??$_POST['type']??'')?'maintenance':'hold',admin_url('admin.php?page=adc-vehicle-issues'))));exit;}
	public static function open():void{check_admin_referer('adc_open_vehicle_issue');self::redirect(VehicleIssueService::open(absint($_POST['vehicle_id']??0),sanitize_key(wp_unslash($_POST['type']??'')),sanitize_textarea_field(wp_unslash($_POST['reason']??'')),0,sanitize_text_field(wp_unslash($_POST['review_at']??''))));}
	public static function resolve():void{$id=absint($_POST['id']??0);check_admin_referer('adc_resolve_vehicle_issue_'.$id);self::redirect(VehicleIssueService::resolve($id,sanitize_textarea_field(wp_unslash($_POST['resolution']??''))));}
}
