/** Deterministic stylesheet assembly; runtime loads main.css directly. */
'use strict';

const fs = require('node:fs');
const path = require('node:path');

const cssDir = path.join(__dirname, 'assets', 'css');
const outputFile = path.join(cssDir, 'main.css');
const files = [
  'abstracts/_variables.css',
  'base/_reset.css',
  'base/_typography.css',
  'components/_buttons.css',
  'components/_cards.css',
  'components/_forms.css',
  'components/_icons.css',
  'components/_floating.css',
  'layout/_header.css',
  'layout/_footer.css',
  'layout/_grid.css',
  'pages/_home.css',
  'pages/_cars.css',
  'pages/_account.css',
  'pages/_page.css',
  'themes/_auto-brands.css',
];

const sections = files.map(file => {
  const source = path.join(cssDir, file);
  if (!fs.existsSync(source)) throw new Error(`Missing CSS source: ${file}`);
  return `/* Source: ${file} */\n${fs.readFileSync(source, 'utf8').replace(/\r\n/g, '\n').trimEnd()}\n`;
});
const expected = `/* Generated by node build-css.js. Edit partials, then rebuild. */\n\n${sections.join('\n')}`;

if (process.argv.includes('--check')) {
  if (!fs.existsSync(outputFile) || fs.readFileSync(outputFile, 'utf8').replace(/\r\n/g, '\n') !== expected) {
    throw new Error('main.css is out of date; run node build-css.js');
  }
  process.stdout.write('main.css matches all CSS sources.\n');
} else {
  fs.writeFileSync(outputFile, expected, 'utf8');
  process.stdout.write(`Built ${path.relative(__dirname, outputFile)} from ${files.length} sources.\n`);
}
